<script setup lang="ts">
const props=defineProps<{modelValue:any;schema:any;label?:string;path?:string}>()
const emit=defineEmits<{ 'update:modelValue':[value:any] }>()
const search=ref(''),page=ref(1),picker=ref(false)
const words:Record<string,string>={styles:'風格',body:'內文',text:'文字',year:'年份',date:'日期',position:'位置',icon:'圖示',background:'背景圖片',subtitle:'副標題',subheading:'副標題',intro:'前言',closing:'結語',storeCases:'門市與案例',brandHistory:'品牌沿革',faqGroups:'常見問題',serviceSteps:'服務步驟',hero:'主視覺',suites:'系列組合',gallery:'圖片集',features:'特色',points:'重點',contact:'聯絡資訊',meta:'案例資訊',article:'文章',KITCHEN_CATALOGUES:'系列型錄',PRODUCT_CATALOGUES:'產品型錄',PRODUCT_CARE_CATEGORIES:'產品保養',title:'標題',name:'名稱',description:'說明',excerpt:'摘要',image:'圖片',images:'圖片集',cover:'封面',src:'圖片來源',alt:'替代文字',url:'連結',href:'連結',to:'目標連結',route:'頁面網址',label:'文字',heading:'段落標題',paragraphs:'段落',bullets:'清單',links:'相關連結',sections:'內容區塊',slug:'網址識別碼',id:'識別碼',copy:'頁面文字與圖片',slides:'首頁輪播',services:'廚電品牌',stores:'門市',phone:'電話',address:'地址',hours:'營業時間',email:'電子郵件',enabled:'上架',featured:'推薦',sort:'排序',cmsSettings:'區塊顯示與搜尋設定',visible:'顯示此區塊',summary:'文章資訊',detail:'文章內文',items:'項目',category:'分類',newsArticles:'消息列表',KITCHEN_SERIES_PAGES:'廚房系列',KITCHEN_STYLES:'系列導覽',seo:'搜尋設定',seoTitle:'搜尋標題',seoDescription:'搜尋摘要',publishedAt:'發布日期',displayDate:'顯示日期',videoId:'YouTube 影片 ID',leftNav:'左側導覽',rightNav:'右側導覽',sitemapGroups:'網站導覽',zh:'中文名稱',en:'英文名稱'}
const title=computed(()=>props.schema.label||words[props.label||'']||props.label||'內容')
const fields=computed(()=>Object.entries(props.schema.fields||{}).filter(([,s]:any)=>!Object.hasOwn(s,'fixed')&&!s.hidden) as [string,any][])
const rows=computed(()=>Array.isArray(props.modelValue)?props.modelValue.map((value:any,index:number)=>({value,index})).filter((r:any)=>JSON.stringify(r.value).toLowerCase().includes(search.value.toLowerCase())):[])
const pages=computed(()=>Math.max(1,Math.ceil(rows.value.length/10)))
watch(search,()=>page.value=1)
function set(key:string,value:any){emit('update:modelValue',{...props.modelValue,[key]:value})}
function item(index:number,value:any){const a=[...(props.modelValue||[])];a[index]=value;emit('update:modelValue',a)}
function move(index:number,step:number){const a=[...(props.modelValue||[])];if(index+step<0||index+step>=a.length)return;[a[index],a[index+step]]=[a[index+step],a[index]];if(props.schema.source)a.forEach((v:any,i:number)=>v.sort=i);emit('update:modelValue',a)}
function add(){const t=JSON.parse(JSON.stringify(props.schema.template??''));if(t&&typeof t==='object'&&!Array.isArray(t)){if('id'in t)t.id=typeof t.id==='number'?Math.max(0,...(props.modelValue||[]).map((v:any)=>Number(v.id)||0))+1:crypto.randomUUID();if('slug'in t)t.slug='new-'+crypto.randomUUID().slice(0,8);if(t.summary)t.summary.title='新增內容';if('title'in t)t.title='新增內容';if('name'in t)t.name='新增項目'}emit('update:modelValue',[...(props.modelValue||[]),t]);search.value='';page.value=Math.ceil(((props.modelValue?.length||0)+1)/10)}
function remove(index:number){emit('update:modelValue',props.modelValue.filter((_:any,i:number)=>i!==index));page.value=Math.min(page.value,Math.max(1,Math.ceil((props.modelValue.length-1)/10)))}
function caption(value:any,index:number){return typeof value==='object'&&value?(value.summary?.title||value.title||value.name||value.label||value.heading||value.model||`項目 ${index+1}`):String(value||`項目 ${index+1}`).slice(0,70)}
</script>
<template>
 <fieldset v-if="schema.type==='object'" class="cms-fields"><legend v-if="label">{{ title }}</legend><AdminFields v-for="[key,field] in fields" :key="key" :model-value="modelValue?.[key]" :schema="field" :label="key" :path="`${path||''}.${key}`" @update:model-value="set(key,$event)" /></fieldset>
 <section v-else-if="schema.type==='array'" class="cms-array"><div class="cms-section-heading"><strong>{{ title }} <span class="cms-count">{{ modelValue?.length||0 }}</span></strong><button v-if="!schema.source" type="button" class="cms-button" @click="add">新增項目</button></div><label v-if="(modelValue?.length||0)>10" class="cms-search"><input v-model="search" :aria-label="`搜尋${title}`" placeholder="搜尋項目" /></label><details v-for="row in rows.slice((page-1)*10,page*10)" :key="row.value?.id||row.index" class="cms-array-row"><summary>{{ caption(row.value,row.index) }}</summary><div class="cms-actions"><button type="button" class="cms-button" :disabled="row.index===0" @click="move(row.index,-1)">上移</button><button type="button" class="cms-button" :disabled="row.index===modelValue.length-1" @click="move(row.index,1)">下移</button><button type="button" class="cms-button" :disabled="schema.source||modelValue.length<=(schema.min||0)" @click="remove(row.index)">移除此項</button></div><AdminFields :model-value="row.value" :schema="schema.item" :path="`${path||''}.${row.index}`" @update:model-value="item(row.index,$event)" /></details><div v-if="pages>1" class="cms-actions"><button type="button" class="cms-button" :disabled="page===1" @click="page--">上一頁</button><span>{{ page }} / {{ pages }}</span><button type="button" class="cms-button" :disabled="page>=pages" @click="page++">下一頁</button></div></section>
 <label v-else-if="schema.enum" class="cms-field">{{ title }}<select :value="modelValue" @change="emit('update:modelValue',($event.target as HTMLSelectElement).value)"><option v-for="v in schema.enum" :key="v" :value="v">{{ ({latest:'最新消息',activities:'優惠活動',video:'影音'} as any)[v]||v }}</option></select></label>
 <label v-else-if="schema.type==='boolean'" class="cms-checkbox"><input type="checkbox" :checked="modelValue" @change="emit('update:modelValue',($event.target as HTMLInputElement).checked)" />{{ title }}</label>
 <label v-else-if="schema.type==='number'" class="cms-field">{{ title }}<input type="number" :value="modelValue" @input="emit('update:modelValue',Number(($event.target as HTMLInputElement).value))" /></label>
 <div v-else class="cms-field"><label>{{ title }}<textarea :readonly="schema.readOnly" v-if="!schema.format&&!schema.identity" :value="modelValue??''" rows="2" @input="emit('update:modelValue',($event.target as HTMLTextAreaElement).value)" /><input v-else :readonly="schema.readOnly" :value="modelValue??''" @input="emit('update:modelValue',($event.target as HTMLInputElement).value)" /></label><template v-if="schema.format==='media'||label==='pdfUrl'"><AdminImage v-if="modelValue&&!String(modelValue).endsWith('.pdf')" :src="modelValue" :alt="title" class="cms-field-thumbnail" /><button type="button" class="cms-button" @click="($event.currentTarget as HTMLButtonElement).focus();picker=true">從媒體庫選擇</button><AdminDialog :open="picker" title="選擇素材" wide @close="picker=false"><AdminMediaGrid picking :kind="label==='pdfUrl'||label==='brochureUrl'?'pdf':'image'" @select="emit('update:modelValue',$event.src);picker=false" /></AdminDialog></template></div>
</template>
