<script setup lang="ts">
const props=defineProps<{id:string}>()
const {api,session,message}=useCmsAdmin()
const doc=ref<any>(null),body=ref<any>({}),baseline=ref(''),error=ref(''),notice=ref(''),busy=ref(false),preview=ref(false),mobile=ref(false)
const dirty=computed(()=>JSON.stringify(body.value)!==baseline.value)
function reload(){if(!dirty.value||window.confirm('重新載入會捨棄尚未儲存內容，確定繼續？'))void load()}
async function load(){error.value='';try{doc.value=await api('documents/'+props.id);body.value=JSON.parse(JSON.stringify(doc.value.body));baseline.value=JSON.stringify(body.value)}catch(e){error.value=message(e)}}
watch(()=>props.id,load,{immediate:true})
async function action(action:string,version?:string){if(busy.value)return false;busy.value=true;error.value='';notice.value='';try{const r=await api('documents/'+props.id,{method:'POST',body:{action,revision:doc.value.revision,body:body.value,version}});doc.value={...doc.value,...r};if(action==='restore')await load();else if(action==='save')baseline.value=JSON.stringify(body.value);doc.value.versions=(await api('documents/'+props.id)).versions;notice.value=({save:'草稿已儲存，官網尚未變更。',publish:'已發布，官網新請求會顯示此版本。',unpublish:'已下架。',restore:'舊版本已還原為草稿，發布後才會更新官網。'} as any)[action];return true}catch(e){error.value=message(e);return false}finally{busy.value=false}}
async function showPreview(event:Event){const trigger=event.currentTarget as HTMLButtonElement;if(dirty.value&&!(await action('save')))return;await nextTick();trigger.focus();preview.value=true}
const previewPath=ref('')
const previewChoices=computed(()=>{const b=body.value;const id=props.id;if(id==='news-articles')return b.items.map((i:any)=>({label:i.summary.title,path:`/news/${i.summary.category}/${i.slug}`}));if(id==='knowledge-articles')return b.items.map((i:any)=>({label:i.summary.title,path:`/knowledge/design/${i.slug}`}));if(id==='data-kitchenSeries')return b.KITCHEN_SERIES_PAGES.map((i:any)=>({label:i.title||i.name||i.slug,path:`/home-style/${i.slug}`}));if(id==='data-storeCases')return b.storeCases.map((i:any)=>({label:i.title||i.name,path:`/gallery/${i.slug}`}));if(id==='custom-cases')return b.items.map((i:any)=>({label:i.title,path:`/design-inspiration/${i.id}`}));return []})
const previewUrl=computed(()=>`${previewPath.value||doc.value?.route||'/'}${(previewPath.value||doc.value?.route||'').includes('?')?'&':'?'}cmsPreview=${encodeURIComponent(props.id)}`)
function beforeUnload(e:BeforeUnloadEvent){if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(()=>window.addEventListener('beforeunload',beforeUnload));onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload))
onBeforeRouteLeave(()=>!dirty.value||window.confirm('尚有未儲存內容，確定離開？'))
onBeforeRouteUpdate(()=>!dirty.value||window.confirm('尚有未儲存內容，確定切換？'))
</script>
<template><section><p v-if="error" class="cms-error" role="alert">{{ error }} <button type="button" class="cms-button" @click="reload">重新載入</button></p><template v-if="doc"><div class="cms-heading"><h1>{{ doc.title }}</h1><div class="cms-actions"><button class="cms-button" :disabled="busy" @click="showPreview">儲存並預覽</button><button class="cms-button" :disabled="busy||!dirty" @click="action('save')">儲存草稿</button><button v-if="session?.role==='admin'" class="cms-button cms-button-gold" :disabled="busy||dirty" @click="action('publish')">發布</button></div></div><p v-if="notice" class="cms-notice" role="status">{{ notice }}</p><div class="cms-editor-meta"><span>{{ dirty?'尚未儲存':doc.draftId===doc.publishedId?'目前已發布':'草稿' }}</span><NuxtLink to="/admin/content">返回內容列表</NuxtLink><button v-if="session?.role==='admin'&&doc.publishedId" class="cms-button" :disabled="busy" @click="action('unpublish')">下架</button></div><div class="cms-panel cms-resource-form"><AdminFields v-model="body" :schema="doc.schema" /></div><details class="cms-panel cms-history"><summary>版本紀錄</summary><div v-for="version in doc.versions" :key="version.id" class="cms-history-row"><span>{{ new Date(version.createdAt).toLocaleString('zh-TW') }} · {{ version.actor||'初始內容' }}</span><button v-if="session?.role==='admin'" class="cms-button" :disabled="busy||dirty" @click="action('restore',version.id)">還原成草稿</button></div></details><AdminDialog :open="preview" title="官網草稿預覽" wide @close="preview=false"><div class="cms-actions"><select v-if="previewChoices.length" v-model="previewPath" aria-label="預覽頁面"><option value="">列表／預設頁面</option><option v-for="p in previewChoices" :key="p.path" :value="p.path">{{ p.label }}</option></select><button class="cms-button" @click="mobile=!mobile">{{ mobile?'切換桌機':'切換手機' }}</button><a :href="previewUrl" target="_blank" rel="noopener noreferrer" class="cms-button">另開完整頁面</a></div><iframe :src="previewUrl" title="官網草稿預覽" class="cms-live-preview" :class="{'cms-live-mobile':mobile}" /></AdminDialog></template></section></template>
