<script setup lang="ts">
definePageMeta({layout:'admin'})
const route=useRoute(),{api,message}=useCmsAdmin()
const query=ref(''),category=ref('全部'),page=ref(1),error=ref('')
const {data:docs,refresh,error:loadError}=await useAsyncData<any[]>('cms-documents',()=>api('documents'))
const categories=computed(()=>['全部',...new Set((docs.value||[]).map(d=>d.category))])
const filtered=computed(()=>(docs.value||[]).filter(d=>(category.value==='全部'||d.category===category.value)&&`${d.title} ${d.id}`.toLowerCase().includes(query.value.toLowerCase())))
watch([query,category],()=>page.value=1)
</script>
<template><div class="cms-page"><p v-if="loadError" class="cms-error" role="alert">{{ useCmsAdmin().message(loadError) }}</p><AdminResourceEditor v-if="typeof route.query.edit==='string'" :key="route.query.edit" :id="route.query.edit" /><template v-else><div class="cms-heading"><h1>網站內容</h1><button class="cms-button" @click="refresh()">重新整理</button></div><p class="cms-muted">選擇內容區域後，可新增項目、編輯及調整順序。</p><div class="cms-content-tools"><label class="cms-search"><input v-model="query" aria-label="搜尋內容" placeholder="搜尋內容" /></label><select v-model="category" aria-label="內容分類"><option v-for="c in categories" :key="c">{{ c }}</option></select></div><div class="cms-panel"><NuxtLink v-for="d in filtered.slice((page-1)*20,page*20)" :key="d.id" :to="{path:'/admin/content',query:{edit:d.id}}" class="cms-resource-row"><div><strong>{{ d.title }}</strong><small>{{ d.category }} · {{ d.route }}</small></div><span class="cms-status" :class="d.publishedId===d.draftId?'published':'draft'">{{ !d.publishedId?'未發布':d.publishedId===d.draftId?'已發布':'有新草稿' }}</span></NuxtLink><p v-if="!filtered.length" class="cms-empty">沒有符合的內容</p></div><div class="cms-actions cms-pagination"><button class="cms-button" :disabled="page<=1" @click="page--">上一頁</button><span>{{ page }} / {{ Math.max(1,Math.ceil(filtered.length/20)) }}</span><button class="cms-button" :disabled="page*20>=filtered.length" @click="page++">下一頁</button></div><p v-if="error" role="alert" class="cms-error">{{ error }}</p></template></div></template>
