<script setup lang="ts">
definePageMeta({layout:'admin'})
const {api,message}=useCmsAdmin(),tab=ref('inbox'),q=ref(''),page=ref(1),editing=ref<any>(null),error=ref(''),busy=ref(false)
const {data:rows,refresh,error:loadError}=await useAsyncData<any[]>('cms-inbox',()=>api(tab.value),{watch:[tab]})
const filtered=computed(()=>(rows.value||[]).filter(r=>JSON.stringify(r).includes(q.value)))
const statuses=computed(()=>tab.value==='inbox'?['待處理','處理中','已完成','垃圾訊息']:['待審核','已核准','已拒絕'])
watch([tab,q],()=>page.value=1)
async function save(){busy.value=true;error.value='';try{await api(tab.value+'/'+editing.value.id,{method:'POST',body:{status:editing.value.status,note:editing.value.note||'',revision:editing.value.revision}});editing.value=null;await refresh()}catch(e){error.value=message(e)}finally{busy.value=false}}
</script>
<template><div class="cms-page"><p v-if="loadError" class="cms-error" role="alert">{{ useCmsAdmin().message(loadError) }}</p><div class="cms-heading"><h1>收件與留言</h1></div><div class="cms-tabs"><button :class="{active:tab==='inbox'}" @click="tab='inbox'">表單收件</button><button :class="{active:tab==='comments'}" @click="tab='comments'">留言審核</button></div><label class="cms-search"><input v-model="q" aria-label="搜尋收件" placeholder="搜尋姓名、內容或狀態" /></label><div class="cms-panel"><button v-for="r in filtered.slice((page-1)*20,page*20)" :key="r.id" class="cms-resource-row" @click="editing={...r};error=''"><div><strong>{{ r.name||r.body?.name||r.body?.contactName }}</strong><small>{{ r.kind==='franchise'?'加盟申請':r.kind==='builder'?'建案預約':r.route }} · {{ new Date(r.createdAt).toLocaleString('zh-TW') }}</small></div><span>{{ r.status }}</span></button><p v-if="!filtered.length" class="cms-empty">目前沒有符合的紀錄</p></div><div class="cms-actions cms-pagination"><button class="cms-button" :disabled="page===1" @click="page--">上一頁</button><span>{{ page }}</span><button class="cms-button" :disabled="page*20>=filtered.length" @click="page++">下一頁</button></div><AdminDialog :open="!!editing" title="處理紀錄" @close="editing=null"><form v-if="editing" class="cms-form" @submit.prevent="save"><dl class="cms-inbox-detail"><template v-for="(value,key) in editing.body||{name:editing.name,email:editing.email,comment:editing.comment,route:editing.route}" :key="key"><dt>{{ ({name:'姓名',contactName:'聯絡人',phone:'電話',email:'Email',company:'公司',note:'備註',comment:'留言',route:'頁面',experience:'經驗',budget:'預算',area:'地區',timeline:'預計時間',gender:'性別',age:'年齡',residence:'居住地',education:'學歷',occupation:'職業',lineId:'LINE ID',contactTimes:'方便聯繫時間',funding:'資金來源',storeType:'店面資訊',storeAddress:'店面地址',storeWidth:'店面寬（公尺）',storeArea:'實際坪數',team:'經營團隊',reasons:'選擇櫻花原因',concerns:'最在意的細節',motivation:'創業原因',sources:'得知加盟訊息',consent:'同意資料使用',consentVersion:'同意版本',consentedAt:'同意時間'} as any)[key]||key }}</dt><dd>{{ Array.isArray(value) ? value.join('、') : value }}</dd></template></dl><label>處理狀態<select v-model="editing.status"><option v-for="s in statuses" :key="s">{{ s }}</option></select></label><label v-if="tab==='inbox'">內部備註<textarea v-model="editing.note" rows="4" /></label><p v-if="error" class="cms-error" role="alert">{{ error }}</p><button class="cms-button cms-button-gold" :disabled="busy">儲存處理結果</button></form></AdminDialog></div></template>
