<script setup lang="ts">
definePageMeta({layout:'admin'})
const {api,session}=useCmsAdmin()
const {data:docs,error:loadError}=await useAsyncData<any[]>('cms-overview',()=>api('documents'))
const drafts=computed(()=>(docs.value||[]).filter(d=>d.draftId!==d.publishedId))
const recent=computed(()=>(docs.value||[]).toSorted((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,8))
const {data:inbox}=await useAsyncData<any[]>('cms-inbox-count',()=>session.value?.role==='admin'?api('inbox'):Promise.resolve([]))
</script>
<template><div class="cms-page"><p v-if="loadError" class="cms-error" role="alert">{{ useCmsAdmin().message(loadError) }}</p><div class="cms-heading"><h1>工作台總覽</h1><NuxtLink to="/admin/home" class="cms-button cms-button-gold">編輯首頁</NuxtLink></div><div class="cms-metrics"><NuxtLink to="/admin/content" class="cms-metric"><div>網站內容<strong>{{ docs?.length||0 }}</strong></div></NuxtLink><NuxtLink to="/admin/content" class="cms-metric"><div>待發布草稿<strong>{{ drafts.length }}</strong></div></NuxtLink><NuxtLink v-if="session?.role==='admin'" to="/admin/inbox" class="cms-metric"><div>待處理收件<strong>{{ inbox?.filter(i=>i.status==='待處理').length||0 }}</strong></div></NuxtLink></div><div class="cms-overview-bottom"><section class="cms-panel"><div class="cms-section-heading"><h2>最近編輯</h2></div><NuxtLink v-for="d in recent" :key="d.id" :to="{path:'/admin/content',query:{edit:d.id}}" class="cms-resource-row"><strong>{{ d.title }}</strong><span>{{ new Date(d.updatedAt).toLocaleDateString('zh-TW') }}</span></NuxtLink></section><section class="cms-panel"><div class="cms-section-heading"><h2>待發布草稿</h2></div><NuxtLink v-for="d in drafts.slice(0,8)" :key="d.id" :to="{path:'/admin/content',query:{edit:d.id}}" class="cms-resource-row">{{ d.title }}</NuxtLink><p v-if="!drafts.length" class="cms-empty">目前沒有待發布草稿</p></section></div></div></template>
